FROM ghcr.io/mspass-team/mspass:latest

LABEL maintainer="Ian Wang <yinzhi.wang.cug@gmail.com>"
ENV PFPATH=/test/pf

USER root

RUN apt-get update && apt-get install -y build-essential cmake && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install numpy

ADD cxx /parallel_pwmig/cxx
ADD data /parallel_pwmig/data
ADD setup.py /parallel_pwmig/setup.py
ADD python /parallel_pwmig/python

RUN MSPASS_HOME=/usr/local python3 -m pip install -C--global-option=build -C--global-option=--debug /parallel_pwmig -v --no-build-isolation


RUN pip3 install vtk

RUN conda install pygmt

